### PR TITLE
Closes #245: Fix project type + Fix project removal states/deletion logi...

### LINKED ISSUE #245: Projects: Listing /v1/projects returns type: 'account' resources
Projects are coming back with `type: 'account'` (and `kind: 'project'`) instead of `type: 'project'`

### PR DESCRIPTION
**Pull request by sidharthamani**
@ibuildthecloud

### CODE REVIEW

File: code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java [hunk 1]
```diff
@@ -75,7 +74,7 @@ public Account getAccountByExternalId(String externalId, String externalType) {
                 .where(
                         ACCOUNT.EXTERNAL_ID.eq(externalId)
                         .and(ACCOUNT.EXTERNAL_ID_TYPE.eq(externalType))
-                        .and(ACCOUNT.STATE.eq("active"))
+                        .and(ACCOUNT.STATE.ne("purged"))
```
Comment (sidharthamani) [inline code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java]: spoke to @vincent99 ... all projects not in "purged" state should be shown in the API response

File: code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/ProjectResourceManager.java [hunk 2]
```diff
@@ -194,13 +191,22 @@ private String getExternalId(String externalId, String externalIdType, String jw
...
+    @Override
+    protected Object removeFromStore(String type, String id, Object obj, ApiRequest apiRequest) {
         if (!(obj instanceof Account)) {
             return new Object();
         }
         String token = getTokenFromRequest(apiRequest);
-        objectProcessManager.executeStandardProcess(StandardProcess.DEACTIVATE, obj,
-                ProcessUtils.chainInData(new HashMap<String, Object>(), AccountConstants.ACCOUNT_DEACTIVATE, AccountConstants.ACCOUNT_REMOVE));
-        Account deletedAccount = (Account) objectManager.reload(obj);
+        try {
```
Comment (sidharthamani) [inline code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/ProjectResourceManager.java]: should be able to remove projects in "active" and "inactive" states.

File: code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java [hunk 3]
```diff
@@ -47,8 +47,7 @@ public Account getAccountById(Long id) {
                 .selectFrom(ACCOUNT)
                 .where(
                         ACCOUNT.ID.eq(id)
-                        .and(ACCOUNT.STATE.eq("active")
-                        .and(ACCOUNT.REMOVED.isNull()))
+                        .and(ACCOUNT.STATE.ne("purged"))
```
Comment (ibuildthecloud) [inline code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java]: `io.cattle.platform.iaas.api.auth.impl.GithubOAuthImpl.getAccount(ApiRequest)` uses this method.  I think this may mean that non-active projects will be authenticated.

File: code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java (hunk 1 above)
Comment (ibuildthecloud) [inline code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java]: This is used by `io.cattle.platform.iaas.api.auth.github.GithubTokenHandler.getGithubAccessToken(ApiRequest)`  is this really a safe change?

File: code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java [hunk 4]
```diff
@@ -104,7 +103,7 @@ public Account getAccountByUuid(String uuid) {
                 .selectFrom(ACCOUNT)
                 .where(
                         ACCOUNT.UUID.eq(uuid)
-                        .and(ACCOUNT.STATE.eq("active"))
+                        .and(ACCOUNT.STATE.ne("purged"))
```
Comment (ibuildthecloud) [inline code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java]: Used by `io.cattle.platform.iaas.api.auth.impl.TokenAccountLookup.getAccount(ApiRequest)`, is this safe?

**Comment by ibuildthecloud** [comment]
@sidharthamani, we need to review this with @vincent99.  I think these changes for `ne("purged")` may have some bad side effects.  I think what you want is that `io.cattle.platform.iaas.api.auth.dao.impl.AuthDaoImpl.getAccessibleProjects(String, List<String>, List<String>)` should change to `ne("purged")` and then `io.cattle.platform.iaas.api.auth.github.ProjectResourceManager.listInternal(SchemaFactory, String, Map<Object, Object>, ListOptions)` should change to not call getAccountById but instead `ObjectManager.loadResource`.
